---
title: Historical Bushfire Boundaries
subtitle: Locations and extents of historical bushfires and burning events, from Geoscience Australia (GA).
format:
  360-analysis-html: default
author: Dean Marchiori
date: last-modified
code-fold: true
---

```{r}
library(tidyverse)
library(sf)
library(here)
library(gganimate)
library(themes360info)
```

Read in data. For source and info see `data/README.md`  

```{r}
fires_raw <- read_sf(here("data", "raw", "fire_history",
    "Historical_Bushfire_Boundaries.geojson"))
```

Process data to keep SE Australia bushfires only (not prescribed burns) from 2000 onwards. Many fires did not have an `ignition_date` so these were removed. 

```{r}
fires <- fires_raw |>
    filter(
        state %in% c(
            "ACT (Australian Capital Territory)",
            "NSW (New South Wales)",
            "VIC (Victoria)",
            "TAS (Tasmania)",
            "QLD (Queensland)",
            "SA (South Australia)"
        ),
        fire_type == "Bushfire",
        !is.na(ignition_date)
    ) |>
    mutate(year = year(ignition_date)) |>
    select(year) |>
    filter(year > 1980) |>
    st_make_valid() |>
    st_transform(3857) |>
    group_by(year) |>
    summarise(geometry = st_union(geometry)) |>
    rmapshaper::ms_simplify(keep_shapes = TRUE)
```


```{r}
#| label: aus-outline

aus_coast <-
    here("data", "raw", "fire_history", "aus-outline.gpkg") |>
    read_sf()
``` 

```{r}
# produce animation
anim <- ggplot() +
    geom_sf(data = aus_coast, colour = "lightgrey", fill = NA, alpha = 0.4,
        inherit.aes = FALSE) +
    geom_sf(aes(group = year), data = fires, fill = "red", lwd = 0, alpha = 0.4,
        inherit.aes = FALSE) +
    theme_void() +
    transition_time(year) +
    gganimate::shadow_wake(0.1, wrap = FALSE, exclude_phase = NULL) +
    labs(title = "Year: {round(frame_time,0)}") +
    coord_sf(crs = st_crs(fires), datum = NA)

# export as a library of svgs
animate(anim,
    renderer = file_renderer(dir = here("data", "final", "anim")),
    device = "svglite",
    nframes = 200,
    width = 6.4,
    height = 6,
    bg = "transparent")
```

## Additional WA zoom in  

```{r}
fires_wa <- fires_raw |>
    filter(
        state %in% c(
            "WA (Western Australia)"
        ),
        fire_type == "Bushfire",
        !is.na(ignition_date)
    ) |>
    mutate(year = year(ignition_date)) |>
    select(year) |>
    filter(year > 2000) |>
    st_make_valid() |>
    group_by(year) |>
    summarise(geometry = st_union(geometry)) |>
    rmapshaper::ms_simplify(keep_shapes = TRUE)  |>
    st_transform(3857)

anim_wa <- ggplot() +
    geom_sf(data = aus_coast, colour = "lightgrey", fill = NA, alpha = 0.4,
        inherit.aes = FALSE) +
    geom_sf(aes(group = year), data = fires_wa, fill = "red", alpha = 0.4,
        inherit.aes = FALSE) +
    theme_void() +
    transition_time(year) +
    gganimate::shadow_wake(0.1, wrap = FALSE, exclude_phase = NULL) +
    labs(title = "Year: {round(frame_time,0)}") +
    coord_sf(crs = st_crs(fires_wa))

# export as a library of svgs
animate(anim_wa,
    renderer = file_renderer(dir = "data", "final", "anim_wa"),
    device = "svglite",
    width = 6.4,
    height = 6,
    bg = "transparent")

```

